name: Quality checks

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lint-command:
          - npm run lint-js
          - npm run lint-md-urls-relative
          - npm run lint-md
          - npm run lint-md-consistency
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm install --only=dev
      - name: Lint
        run: ${{ matrix.lint-command }}
